# Generated by Django 4.2.8 on 2024-05-18 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('released_date', models.DateField(default=datetime.date.today, null=True)),
                ('vote_avg', models.FloatField()),
                ('is_adult', models.BooleanField()),
                ('poster_path', models.TextField(null=True)),
                ('genres', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NowMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('released_date', models.DateField(default=datetime.date.today, null=True)),
                ('vote_avg', models.FloatField()),
                ('is_adult', models.BooleanField()),
                ('poster_path', models.TextField(null=True)),
                ('genres', models.CharField(max_length=255)),
            ],
        ),
    ]
